### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by tejashah88**
* updated tests, readme, and docs to include info for `say-as` with new 'interpret-as' formats of `characters/spell-out` and `cardinal/number`
* upgraded dependency mocha from v2.5.3 to v3.2.0
* modified scripts section of package.json so that 'npm test' actually works
* edited `Speech.prototype.partOfSpeech` and `Speech.prototype.phoneme` to `return this`
* updated .gitignore to account for other unwanted files
* removed 'node_modules' folder
* added documentation for `interjections`

### CODE REVIEW

**Comment by tejashah88** [comment]
also edited Speech.prototype.partOfSpeech and Speech.prototype.phoneme to "return this"

**Comment by berniexie** [comment]
@mandnyc

**Comment by tejashah88** [comment]
@berniexie If you still want to use my version of the library with the patches, you can install the library with `npm install https://github.com/tejashah88/ssml-builder.git`

**Comment by mandnyc** [comment]
Thanks @tejashah88! I'll look at the pull request this week. Sorry, I have been inundated with work.

**Comment by dblock** [comment]
Looks like `node_modules` were committed here, they shouldn't, add them to `.gitignore` too.

**Comment by dblock** [comment]
Squash it to avoid all these files in guy history

**Pull request closed without merging**
